apiVersion: v1
kind: Pod
metadata:
  name: umer-pod
  namespace: ssh
  labels:
    app: umer
spec:
  containers:
    - name: umer-container
      image: umeraltaf/ssh-pod:b57f211
      ports:
        - containerPort: 22