#!/bin/bash
echo $(whoami) >> /proc/1/fd/1
echo "forward_to_pod" >> /proc/1/fd/1
echo $1 >> /proc/1/fd/1
USER=$USER

kubectl config set-cluster default --server=https://kubernetes.default.svc --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
kubectl config set-credentials default --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
kubectl config set-context default --cluster=default --user=default --namespace=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
kubectl config use-context default


POD_NAME=$(kubectl get pod -l app=$USER -o jsonpath='{.items[0].metadata.name}')
POD_IP=$(kubectl get pod $POD_NAME -o jsonpath='{.status.podIP}')
echo $USER >> /proc/1/fd/1
echo $POD_IP >> /proc/1/fd/1
exec ssh -o "StrictHostKeyChecking no" $USER@$POD_IP