#!/bin/bash
USER=$1
POD_NAME=$(kubectl get pod -l app=$USER -o jsonpath='{.items[0].metadata.name}')
POD_IP=$(kubectl get pod $POD_NAME -o jsonpath='{.status.podIP}')
exec ssh -o "StrictHostKeyChecking no" -i /root/.ssh/id_rsa $USER@$POD_IP