name: Build and Push SSH Bastian

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Runner
        run: lscpu
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      -
        name: Build and push
        context: ./ssh-bastian
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: umeraltaf/ssh-bastian:latest
